version: '3.8'

services:
  app:
    build: .
    ports:
      - "1337:1337"
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./internal/shared/config:/app/config:ro
