server:
  address: ":1337"
  shutdown_timeout: "30s"

blockchain:
  ethereum_rpc_url: ""  # Will be overridden by ETHEREUM_RPC_URL env var

rate_limit:
  requests_per_minute: 600  # 10 requests per second (Infura-friendly)            
